Feat/izzy navbar
ensign-cs220/portfolio pull request #24
Opened 2023-01-17 01:12 UTC by sapoepsilon

navbar: ✅

demo:
![IzzyMansurov](https://user-images.githubusercontent.com/47342870/212788384-38de8424-665c-446a-9b2f-f022677e3b6a.gif)

2023-01-17 01:14 UTC, sapoepsilon commented
Is linter complaining about tabs vs spaces?  @danielcamargo

2023-01-17 03:09 UTC, danielcamargo requested changes

2023-01-17 03:09 UTC, danielcamargo commented on src/Izzy/index.html
> +                    <a href="#" class="font-fira text-lg hover:opacity-40">./izzyMansurov</a>
```suggestion
                    <a href="#" class="font-mono text-lg hover:opacity-40">./izzyMansurov</a>
```
The correct name of the font is font-mono (in our case, `fira-code`). Check the tailwindcss.config.js file for more info about it.

2023-01-18 00:29 UTC, danielcamargo commented
@sapoepsilon, what are using to screenshot the demo? It would be nice to share that with the rest of the team if you haven't done it already. Thank you!

2023-01-24 03:34 UTC, danielcamargo approved these changes

2023-01-24 03:34 UTC, merged